###############################################################################################################
#||=========================================================================================================||#
#||                                                                                                         ||#
#||                                     SchemManager Config-File                                            ||#
#||                                         Plugin by Zeanon                                                ||#
#||                    Config-Management-System: LightningStorage by JavaFactoryDev                         ||#
#||                                                                                                         ||#
#||=========================================================================================================||#
###############################################################################################################
#                                                                                                             #
###############################################################################################################
# to get information about the custom commands, just type /schem or //schem                                   #
# You don't need to reload the plugin when editing the config, it will automatically detect changes.          #
# You can perform a deep search or deep listing by using -d                                                   #  
# You only need to edit WorldEdit Schematic-Path when you use a path other than the standard WorldEdit path.  #
# Listmax: The maximum amount of schematics per page to be shown.                                             #
# Space Lists: Should there be a blank line before each schem or folder page?                                 #
# Save Funtion Override: Should the basic save function be overridden by the plugin?                          #
# Automatic Reload: Should the plugin automatically reload the Server after it got updated?                   #
###############################################################################################################

Plugin Version: "3.5.2"

WorldEdit Schematic-Path: Default Schematic Path
 
Listmax: 10

Space Lists: true

Save Function Override: true

Automatic Reload: true