name: SchemManager
version: 4.0.0
api-version: 1.14
authors: [Zeanon, JavaFactoryDev]
main: de.zeanon.schemmanager.SchemManager
softdepend: [WorldEdit, FastAsyncWorldEdit, WorldGuard, PlugMan]
commands:
  schemmanager: