name: SchemManager
version: 3.7.1
api-version: 1.14
authors: [Zeanon, JavaFactoryDev]
main: de.zeanon.schemmanager.SchemManager
softdepend: [PlugMan, WorldEdit, WorldGuard, FastAsyncWorldEdit]
commands:
  schemmanager: