name: SchemManager
version: 4.1.7
api-version: 1.14
authors: [Zeanon, JavaFactoryDev]
website: https://github.com/Zeanon/SchemManager
main: de.zeanon.schemmanager.SchemManager
softdepend: [WorldEdit, FastAsyncWorldEdit, WorldGuard, PlugMan]
commands:
  schemmanager: