name: SchemManager
version: 3.6.8
api-version: 1.14
authors: [Zeanon, JavaFactoryDev]
main: de.zeanon.schemmanager.SchemManager
loadbefore: [FastAsyncWorldEdit, WorldEdit, WorldGuard]
commands:
  schemmanager: