name: ${project.name}
version: 2.3
api-version: 1.14
description: ${project.description}
authors: [Zeanon, JavaFactoryDev]
website: ${project.url}
main: de.zeanon.schemmanager.SchemManager
softdepend: [WorldEdit, FastAsyncWorldEdit, WorldGuard, PlugMan]
commands:
  schemmanager:
    description: The basic command for SchemManager
    aliases: sm