name: ${project.name}
version: ${project.version}
description: ${project.description}
author: Zeanon
website: ${project.url}
main: de.zeanon.schemmanager.SchemManager
api-version: 1.15
softdepend: [ WorldEdit, FastAsyncWorldEdit, WorldGuard, PlugMan ]
commands:
  schemmanager:
    description: The basic command for SchemManager
    aliases: sm