name: ${project.name}
version: ${project.version}
description: ${project.description}
author: Zeanon
website: ${project.url}
main: de.zeanon.schemmanager.SchemManager
softdepend: [WorldEdit, FastAsyncWorldEdit, WorldGuard, PlugMan]
commands:
  schemmanager:
    description: The basic command for SchemManager
    aliases: sm